title: Audrey Checketts
logo: docs/assets/audPortfolioHeadshot.png
description:   Software QA | Artist | Musician
url: https://www.linkedin.com/in/audrey-checketts/
#show_downloads: true
theme: jekyll-theme-slate
