title: Audrey Checketts
logo: docs/assets/myimage.png
description: Software QA | Artist | Musician
website: https://www.linkedin.com/in/audrey-checketts/
#show_downloads: true
theme: jekyll-theme-minimal
