title: Audrey Checketts
logo: docs/assets/audPortfolioHeadshot.png
description:   Software QA | Artist | Musician
website: https://www.linkedin.com/in/audrey-checketts/
#show_downloads: true
theme: jekyll-swiss
